spring:
  jackson:
    serialization-inclusion: non_null

  data:
    rest:
      basePath: /api

  datasource:
    url: jdbc:h2:mem:music

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  hateoas:
    use-hal-as-default-json-media-type: true

  mandatory-file-encoding: UTF-8

security:
  sessions: stateless
  basic:
    enabled: false

logging:
  level:
    root: info

app:
  hash-algorithm: SHA-256
  hash-secret-key: this-will-change-to-environment-variable
