debug: true

spring:
  jackson:
    serialization-inclusion: non_null

  data:
    rest:
      basePath: /api

  datasource:
    url: jdbc:h2:mem:music

app:
  hash-algorithm: SHA-256
  hash-secret-key: this-will-change-to-environment-variable
